"use client";

import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { ThemeSwitcher } from "@/components/ThemeSwitcher";

const logs = [
  {
    date: "2026-09-09",
    title: "Self-connect guard, ellipsis rendering fix, persistent sessions, themes, and more",
    description:
      "A batch of fixes and improvements. (1) You can no longer connect to your own Peer ID \u2014 the Connect button disables itself and explains why. (2) Fixed the sending/receiving progress bars literally showing the six characters \u201c\\u2026\u201d instead of an ellipsis \u2014 turns out JSX doesn't decode \\u escapes in attribute string literals, only inside real JS expressions, so those labels needed the actual \u2018\u2026\u2019 glyph. (3) Visiting DevLogs and coming back used to reset your Peer ID and drop any live connection, because navigating between pages unmounted the whole session hook. The session (peer id, RTCPeerConnection, DataChannel, transfer state) now lives in a context provider mounted at the layout level, above both pages, so it survives navigating away and back. (4) Added the Google Search Console site-verification meta tag. (5) Rebuilt the backend \u201cwaking up\u201d screen with an animated client/server handshake visual, rotating status messages, and an expandable note explaining the free-tier cold start. (6) Added 8 selectable themes (Void, Neon Synthwave, Abyssal Teal, Solar Flare, Forest Whisper, Royal Amethyst, Arctic Frost, and Sandstorm \u2014 the last two are light themes) via a palette icon in the header; your choice is remembered in localStorage and applied instantly with no flash on reload. (7) Re-checked every touched screen at mobile widths to keep things comfortable on small screens.",
  },
  {
    date: "2026-09-07",
    title: "Fixed connections stuck on \u201cConnected\u201d with the channel never opening",
    description:
      "Found a bug introduced while re-architecting the signaling module: on the accepting side, any ICE candidates that arrived before the user clicked Accept were queued (since the remote description wasn't set yet), but that queue was only ever flushed inside the code path that handles an incoming answer \u2014 which the accepting side never receives. Those early candidates were silently dropped, ICE negotiation stalled, and the DataChannel never opened, even though the signaling handshake itself succeeded. Fixed by flushing queued candidates right after the accepting side sets its remote description, not just after receiving an answer.",
  },
  {
    date: "2026-09-06",
    title: "Fixed \u201cpublic: Must be a CryptoKey\u201d crash on send",
    description:
      "Root-caused a race condition in the ECDH handshake: only the calling peer sent its public key as soon as the DataChannel opened, while the answering peer waited to receive a key before sending its own back. That meant the UI could show \u201cConnected\u201d well before both sides actually held each other's public key, so hitting Send File in that window called deriveKey with a null peer key and crashed. Both sides now send their public key the instant their DataChannel opens, the UI tracks a dedicated \u201csecure channel ready\u201d state, and Send File is disabled until it's true.",
  },
  {
    date: "2026-09-06",
    title: "Project restructure + UI refresh",
    description:
      "Split the codebase into clearly separated server/ and client/ packages, broke the old single-file page.js into small focused components and hooks (useVoidShare, useBackendWarmup, ConnectPanel, FileTransferPanel\u2026), and gave the interface a visual pass: ambient background glow, glass-panel cards, live connection/key-exchange status pills, and consistent iconography.",
  },
  {
    date: "2025-08-16",
    title: "Added File Integrity Check",
    description:
      "Added file integrity check using SHA-256 hashing. Now when you send a file, it computes the hash of the file and sends it along with the file. The receiver can verify the integrity of the file by comparing the received hash with the computed hash. This ensures that the file is not tampered with during transmission.",
  },
  {
    date: "2025-08-15",
    title: "Major Bug Fix",
    description:
      "Since the deployment of VoidShare, there was this problem that sometimes while sending a file, a crypto key is not defined error pops up but sometimes the file transfer was working fine. It was because of the race between key exchange and key generation. Sometimes if peers connected before their own keys were generated, the crypto key was not defined. Resolved by waiting for key generation before sending.",
  },
  {
    date: "2025-08-15",
    title: "New feature: QR Codes",
    description:
      "New feature added to VoidShare. Now you can connect to your friend's device using QR codes. Just scan the QR code generated by your friend and you will be connected to their device. This makes it easier to connect with friends without needing to share long peer IDs.",
  },
  {
    date: "2025-08-13",
    title: "Resolved buffer overflow on different devices",
    description:
      "The last buffer overflow issue identified was resolved but only for desktops. Later I saw that on mobile it was still popping up. Turns out the buffer sizes for different devices differ, plus there was a small bug in the code. Resolved by decreasing the chunk size.",
  },
  {
    date: "2025-08-11",
    title: "Resolved backend server sleep issue",
    description:
      "Since the backend and frontend are deployed separately on the free tier of Render, both go to sleep on inactivity. Opening the frontend woke it up, but the backend never got woken. Now when the frontend wakes up, it first pings the backend and waits for it to respond, showing a loading screen in the meantime.",
  },
  {
    date: "2025-08-10",
    title: "Added DevLogs",
    description:
      "DevLogs page added. You can see the development progress and updates of VoidShare here, including earlier dated logs.",
  },
  {
    date: "2025-08-10",
    title: "Added WebRTC Data Channel Buffer Control",
    description: "As mentioned in the previous log, the buffer overflow issue is now resolved and working.",
  },
  {
    date: "2025-08-08",
    title: "Problem Identified",
    description:
      "Major problem found while using the app for a while: buffer overflow when sending large files. Sending is much faster than receiving and the DataChannel's buffer limit is low. Plan: pause sending when the buffer reaches a limit and resume once it drains.",
  },
  {
    date: "2025-08-07",
    title: "Initial Release",
    description:
      "VoidShare is deployed. Peer-to-peer file sharing over WebRTC \u2014 secure, no server involvement for the actual file transfer, files encrypted with ECDH + AES, chunked for speed. Open source and open to contributions.",
  },
];

export default function DevLogs() {
  return (
    <main className="relative min-h-screen px-4 py-10 font-sans">
      <div className="void-glow" />

      <div className="relative z-10 max-w-2xl mx-auto">
        <div className="flex items-center justify-between gap-3 mb-6">
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-sm text-[var(--c-text-muted)] hover:text-[var(--c-text)] transition"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to VoidShare
          </Link>

          <ThemeSwitcher />
        </div>

        <h1 className="text-3xl font-bold text-[var(--c-text)] mb-1">
          Dev<span className="text-[var(--c-accent)]">Logs</span>
        </h1>
        <p className="text-sm text-[var(--c-text-dim)] mb-8">
          A running log of what changed and why, newest first.
        </p>

        <ol className="space-y-4 border-l border-[var(--c-border-strong)] pl-6">
          {logs.map((log, i) => (
            <li key={i} className="relative">
              <span className="absolute -left-[29px] top-1.5 w-2.5 h-2.5 rounded-full bg-[var(--c-accent)] shadow-[0_0_8px_color-mix(in_oklab,var(--c-accent)_70%,transparent)]" />
              <div className="glass-card rounded-xl p-4">
                <p className="text-[11px] text-[var(--c-text-dim)] font-mono">{log.date}</p>
                <h2 className="text-base font-semibold text-[var(--c-text)] mt-0.5 mb-1.5">{log.title}</h2>
                <p className="text-sm text-[var(--c-text-muted)] leading-relaxed">{log.description}</p>
              </div>
            </li>
          ))}
        </ol>
      </div>
    </main>
  );
}
